import tw from 'twrnc';
import {colors} from '../../types/Colors';

export const styles = {
  container: tw`flex-1 bg-[#efeedb]`,
  header: tw`bg-[#efeedb] pt-4 pb-2 px-4 items-left`,
  headerTitle: tw`text-[#55585b] text-[18px] font-semibold`,
  image: tw`w-full h-64 rounded-lg`,
  carousel: tw`h-64 mb-4`,
  carouselContainer: tw`mt-4 mb-4 items-center px-4`,
  carouselItem: tw`w-full h-full overflow-hidden rounded-lg`,
  carouselImage: tw`w-full h-full rounded-lg`,
  infoContainer:tw`bg-gray-50 p-4 rounded-lg mb-4 border border-gray-200`,
  title: tw`text-xl font-bold text-[${colors.yellow}]`,
  location: tw`text-sm text-gray-600 mt-1`,
  status: tw`text-sm text-[${colors.yellow}] mt-1`,
  description: tw`text-sm text-gray-800 mt-3 leading-relaxed`,
  financeContainer: tw`pb-4`,
  parcelaItem: tw`bg-gray-100 rounded-xl px-4 py-3 mb-3 mx-4 flex-row justify-between items-center`,
  parcelaInfo: tw`flex-1`,
  parcelaText: tw`text-sm text-[#55585b]`,
  parcelaStatus: tw`text-sm text-[${colors.yellow}] mt-1`,
  botaoBoleto: tw`bg-[${colors.yellow}] px-3 py-2 rounded-lg mt-2`,
  botaoBoletoTexto: tw`text-white text-sm font-semibold`,
  andamentoContainer: tw`px-4 mt-6 bg-white p-4 pb-4 mb-4`,
  andamentoWrapper: tw`items-center mb-4 mt-4`,
  sectionTitle: tw`text-lg font-semibold mb-4 text-[#55585b]`,
  etapasItem: tw`bg-gray-100 rounded-lg px-3 py-2 mb-2`,
  etapasText: tw`text-sm text-[#55585b]`,
  progressBarBackground: tw`w-full h-3 bg-gray-200 rounded-full`,
  progressBarFill: tw`h-3 rounded-full`,
  progressContainer: tw`mb-4 items-center`,
  comunicadoItem: tw`border-b border-gray-200 pb-3 mb-3`,
  comunicadoTitulo: tw`text-base font-semibold text-[#55585b]`,
  comunicadoData: tw`text-xs text-gray-500 mt-1`,
  section: tw`px-4 mt-4`,
  comunicadoContainer: tw`bg-gray-50 p-4 rounded-lg mb-4 border border-gray-200`,
  comunicadoDescricao: tw`text-sm text-gray-700 mt-2 leading-relaxed`,
  botaoGaleria: tw`bg-[${colors.yellow}] px-4 py-2 rounded-lg flex flex-row ml-4`,
  botaoGaleriaTexto: tw`text-white font-semibold text-base ml-2`,
  iconGaleria: tw`text-white text-sm ml-2`,
  alignGaleria:  tw`flex items-start`,
  sectionContainer: tw`px-4 mt-6`,
  botaoVerMais: tw`bg-[${colors.yellow}] px-2 py rounded-lg items-center justify-center mt-4 mx-4`,
  botaoVerMaisTexto: tw`text-white font-semibold text-base`,
  modalOverlay: tw`flex-1 bg-black/50 justify-center items-center`,
  modalContent: tw`bg-white w-80 p-6 rounded-2xl`,
  label: tw`text-sm font-semibold text-[#55585b] mt-1`,
  value: tw`text-sm text-gray-700 mb-1`,
  botaoFechar: tw`bg-gray-300 px-4 py-2 rounded-lg items-center mt-4`,
  botaoFecharTexto: tw`text-gray-800 font-semibold text-base`,
  card: tw`bg-gray-50 p-4 rounded-lg mb-4 border border-gray-200 mt-4`,
  codigoBarrasContainer: tw`flex-row items-center mt-1 flex-wrap`,
  codigoBarrasText: tw`text-sm text-gray-700 flex-1`,
  modalBottom: tw`w-full py-3 rounded-lg items-center justify-center bg-[${colors.blue}]`,
  modalError: tw`w-full mt-4 py-3 rounded-lg items-center justify-center bg-[${colors.red}]`,
  copyButton: tw`ml-2`,
  copiedButton: tw`text-white text-center font-weight:500`,
  parcelaActions: tw`flex-col items-end justify-start`,
  galeriaButtonContainer: tw`items-center mb-4`,
  etapaTitulo: tw`text-sm font-semibold text-[#55585b] mb-1`,
  backButton: tw`flex flex-row items-center mt-4 mb-2 px-4 justify-center`,
  arrowLeft: tw`absolute left-4`,
  empreendimentoTitle: tw`text-lg font-semibold text-black`,
  sheetBackground: tw`bg-gray-100`,
  sheetContent: tw`p-4`,
  sheetTitle: tw`text-lg font-semibold text-[#55585b] mb-3 text-center`,
  sheetLabel: tw`text-sm font-semibold text-[#55585b] mt-2`,
  sheetValue: tw`text-sm text-gray-700 mb-1`,
  sheetBox: tw`bg-gray-200 p-4 rounded-lg mb-4 border border-gray-200`,
  backdropStyle: tw`bg-black/60`,
  whatsapp: tw`absolute bottom-24 right-5 bg-[#25D366] rounded-full p-4 shadow-lg`,
  topBar: tw`flex-row items-center justify-between px-4 py-2 bg-[#efeedb] relative`,
  menuButton: tw`p-2`,
  menuDropdown: tw`absolute top-12 right-4 bg-white rounded-xl shadow-lg border border-gray-200 z-50 w-48`,
  menuItem: tw`px-4 py-3 border-b border-gray-100`,
  menuLabel: tw`text-[#55585b] text-base`,
};